# Generated by Django 5.2.15 on 2026-06-22 16:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='PermanentBlock',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('scope_type', models.CharField(max_length=32)),
                ('scope_value', models.CharField(max_length=255)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('rule_name', models.CharField(blank=True, default='', max_length=128)),
                ('status_code', models.PositiveSmallIntegerField(default=429)),
                (
                    'message',
                    models.CharField(
                        default='Request blocked by audit enforcement policy',
                        max_length=255,
                    ),
                ),
                ('metadata', models.JSONField(blank=True, default=dict)),
                (
                    'created_at',
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                (
                    'revoked_at',
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    'revoked_by',
                    models.CharField(blank=True, default='', max_length=128),
                ),
                (
                    'revoked_reason',
                    models.CharField(blank=True, default='', max_length=255),
                ),
            ],
            options={
                'verbose_name': 'permanent block',
                'verbose_name_plural': 'permanent blocks',
                'indexes': [
                    models.Index(
                        fields=['scope_type', 'scope_value', 'revoked_at'],
                        name='secenf_active_lookup',
                    ),
                    models.Index(
                        fields=['revoked_at', 'created_at'], name='secenf_admin_listing'
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        condition=models.Q(('revoked_at__isnull', True)),
                        fields=('scope_type', 'scope_value'),
                        name='uniq_active_block_per_scope',
                    )
                ],
            },
        ),
    ]
